# Generated by Django 2.0.2 on 2020-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200628_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes_total_int',
            field=models.IntegerField(default=0),
        ),
    ]
